    {1}.etbcod  
    {1}.etbnom 
    {1}.ufecod   
    {1}.etbinsc 
    {1}.etbcgc 
    {1}.endereco  
    {1}.etbtofne 
    {1}.etbtoffe
    {1}.munic   
    {1}.etbserie 
    {1}.movndcfim 
    {1}.etbfluxo 
    {1}.estcota 
    {1}.vencota
    {1}.RegCod   
    {1}.etbmov  
    {1}.etbcon
